# Generated by Django 6.1 on 2026-08-19 12:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('hall', models.CharField(blank=True, choices=[('HALL1', 'Hall 1'), ('HALL2', 'Hall 2'), ('HALL3', 'Hall 3'), ('HALL4', 'Hall 4'), ('HALL5', 'Hall 5'), ('HALL6', 'Hall 6'), ('HALL7', 'Hall 7'), ('HALL8', 'Hall 8'), ('HALL9', 'Hall 9'), ('HALL10', 'Hall 10'), ('HALL11', 'Hall 11'), ('HALL12', 'Hall 12'), ('HALL13', 'Hall 13'), ('GH1', 'Girls Hostel 1'), ('GH2', 'Girls Hostel 2'), ('GHT', 'Girls Hostel Tower'), ('NANKARI', 'Nankari'), ('IITK_RES', 'Campus residence'), ('OFF', 'Day scholar / off campus')], max_length=20)),
                ('room', models.CharField(blank=True, max_length=20, verbose_name='Room number')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Contact number')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('profile_complete', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
