# Generated by Django 6.1 on 2026-08-19 12:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('glyph', models.CharField(default='?', max_length=4)),
                ('order', models.PositiveSmallIntegerField(default=100)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('zone', models.CharField(choices=[('ACAD', 'Academic area'), ('HALL', 'Halls of residence'), ('SPORT', 'Sports & Gymkhana'), ('SERV', 'Shops, mess & services'), ('OPEN', 'Roads & open campus')], default='ACAD', max_length=10)),
            ],
            options={
                'ordering': ['zone', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('LOST', 'Lost'), ('FOUND', 'Found')], db_index=True, max_length=6)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(help_text='Anything that would let the real owner prove it is theirs.')),
                ('colour', models.CharField(blank=True, max_length=40)),
                ('brand', models.CharField(blank=True, max_length=60)),
                ('place_detail', models.CharField(blank=True, help_text="Narrow it down — 'second floor reading room', 'near the water cooler'.", max_length=140)),
                ('happened_on', models.DateField(default=django.utils.timezone.localdate)),
                ('happened_at', models.TimeField(blank=True, null=True)),
                ('handover', models.CharField(blank=True, choices=[('WITH_ME', "I'm holding it"), ('SECURITY', 'Deposited at the Security Office'), ('HALL_OFFICE', 'Left at the hall office'), ('DEPT', 'Left at the department office'), ('IN_PLACE', 'Left where I found it')], max_length=20)),
                ('secret_detail', models.CharField(blank=True, help_text="Only for found items. Something not visible in the photo — a sticker, the lock screen, what's inside. Claimants must describe it.", max_length=200)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('MATCHED', 'Possible match'), ('CLAIMED', 'Claim in progress'), ('RETURNED', 'Returned'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='items.category')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(help_text='Where it was lost, or where you found it.', on_delete=django.db.models.deletion.PROTECT, related_name='items', to='items.location')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='items/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='items.item')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(choices=[('RULES', 'Rule-based'), ('AI', 'AI agent'), ('HUMAN', 'Spotted by a person')], default='RULES', max_length=10)),
                ('dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('found_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_as_found', to='items.item')),
                ('lost_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_as_lost', to='items.item')),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=240)),
                ('url', models.CharField(blank=True, max_length=200)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['kind', 'status', '-created_at'], name='items_item_kind_f88bb8_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['category', 'kind'], name='items_item_categor_21a6ea_idx'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('lost_item', 'found_item'), name='unique_match_pair'),
        ),
    ]
